### ISSUE TITLE
Requirements for tensorflow version - Does not work with tf2

### ISSUE THREAD

**Issue by kienerj** [clinfo/kGCN#29]
As a suggestion and for others potentially falling into this trap:

The requirements list tensorflow (>1.12). However it should also be added <2.0 as tf2 is incompatible. 
1.13 seems to work (example notebook) also on Windows using anaconda tensorflow-gpu=1.13.

**Comment by sishida21** [comment]
Thank you for your suggestion about the requirements.

Considering your suggestion, I updated the README ( https://github.com/clinfo/kGCN/commit/d410b0dbbbe0949445945ca0d317f2ac4af02947 ).
